UCB - Added entities with relations for users
Tulipanik/Projektowanie_oprogramowania pull request #65
Opened 2024-11-09 13:35 UTC by szymonpoltorak

Dodałem użytkowników i relacje w DB. Niech jeden z architektów sprawdzi, czy wszystko co trzeba jest.
![image](https://github.com/user-attachments/assets/22e8b5a5-5558-42c5-ab02-b9da0fa434e4)

2024-11-10 11:13 UTC, Higunio320 requested changes

2024-11-10 11:13 UTC, Higunio320 commented on backend/src/main/java/pl/edu/pw/ee/backend/entities/order/Order.java
dishes many to many, nie moge dac komentarza nizej

2024-11-10 15:26 UTC, szymonpoltorak commented
Poprawiony diagram:
![cart_dishes](https://github.com/user-attachments/assets/7c90141b-02f3-47db-b9a0-e4146d5b64b5)

2024-11-11 08:14 UTC, Higunio320 approved these changes

2024-11-11 08:15 UTC, merged

2024-11-11 10:51 UTC, Anna3001 commented
@szymonpoltorak w iteracjach, które będziecie realizować nie ma działu prawnego, więc czemu law_departments?

2024-11-11 10:59 UTC, szymonpoltorak commented
> @szymonpoltorak w iteracjach, które będziecie realizować nie ma działu prawnego, więc czemu law_departments?

Bo tam dodaliście go w aktorach, a jak rozmawialiśmy to miałem dodać wszystkich aktorów.

2024-11-11 11:00 UTC, Anna3001 commented
@szymonpoltorak widze, że dałeś catering_companies i to jest okej, ale musi być jeszcze courier_companies z NIP'em, adresem itd. 

UC5 - Dodanie nowej firmy kateringowej
UC12 - Dodanie nowej firmy kurierskiej

2024-11-11 11:02 UTC, Anna3001 commented
> > @szymonpoltorak w iteracjach, które będziecie realizować nie ma działu prawnego, więc czemu law_departments?
> 
> Bo tam dodaliście go w aktorach, a jak rozmawialiśmy to miałem dodać wszystkich aktorów.

Wszystkich, którzy tyczą się części, którą macie realizować, czyli pierwszych dwóch iteracji

2024-11-13 17:52 UTC, szymonpoltorak commented
@Anna3001 podrzucam najbardziej aktualną wersję db pod tym pr'em:
![cart_dishes](https://github.com/user-attachments/assets/0717c811-faaa-497a-926f-5c11dcf88e87)