UCB-auth
Tulipanik/Projektowanie_oprogramowania pull request #68
Opened 2024-11-11 14:28 UTC by szymonpoltorak

Dodałem autoryzację dla użytkowników. Jest możliwość tworzenia ich kont. Ogólnie każdy użytkownik ma to samo hasło w tym momencie i można się tylko na nie logować. 

* Na `localhost:8080/api/v1/swagger-ui/index.html` będzie widać wszystkie endpointy,
* @SzymonRogozinski możesz sobie zobaczyć już jak co jest odsyłane i jak logować użytkowników. Zwracane jest wam JWT i wy musicie je przesyłać w `Authorisation: Bearer <token>`,
* @Anna3001 apropos naszej poprzedniej rozmowy myślę, że CateringCompanyDTO nie ma do końca zastosowania bo to powinno być co w stylu `ExternalCompanyDTO` bo przekazywany jest tam typ firmy w enumie. Z tego powodu wywaliłem encję z bazy `CateringCompanies` i dodałem zamiast niej `ExternalCompanies`. Nazwa jest bardzo myląca,
* Użytkowników można zajrzeć w pliku `BackendApplication.java` i oni są tworzeni wraz z uruchomieniem aplikacji

2024-11-11 14:51 UTC, Anna3001 commented
@szymonpoltorak rozumiem, możesz w wolnej chwili załączyć gdzieś aktualny diagram bazy danych

2024-11-11 14:55 UTC, szymonpoltorak commented
> @szymonpoltorak rozumiem, możesz w wolnej chwili załączyć gdzieś aktualny diagram bazy danych

Diagram jest taki jak w poprzednim PR tylko zmieniła się nazwa CateringCompany na ExternalCompany. Zastanawiałem się nad sensem istnienia encji typu Manager, Storekeeper, Law Department, Courier. Bo tak naprawdę to one są również tylko Userem z odpowiednią rolą

2024-11-11 20:35 UTC, Tulipanik commented
z tym ExternalCompany jest okej. Z tymi użytkownikami zostawiłabym oddzielne encje, aby w razie czego było to łatwiej edytowalne gdyby okazało się, że ktoś potrzebuje więcej informacji, chociaż na potrzeby tych iteracji byłoby okej. Dodatkowo law_department nie jest konieczny, bo ustalaliśmy, że ustawiamy role dla zaplanowanych iteracji, a law_department nie jest w żadnej z tych iteracji

2024-11-11 20:42 UTC, szymonpoltorak commented
Czy w takim wypadku nie powinniśmy mieć `ExternalCompanyDTO` zamiast `CateringCompanyDTO` jak wracamy tam typ firmy?

2024-11-12 17:02 UTC, Higunio320 requested changes

2024-11-12 17:05 UTC, szymonpoltorak commented on backend/src/main/java/pl/edu/pw/ee/backend/api/auth/account/AccountCreationServiceImpl.java
> +        log.info("Creating courier account : {}", request);
Imo nie bo te logi są istotne żeby wiedzieć co się dzieje w aplikacji. Jak odpalasz aplikację na środowisku produkcyjnym to nie wrzucasz wszystkich logów na debug bo jakby tak było to nie wiedziałbyś jak poprawić coś co zgłasza użytkownik, a dane mogą zostać zmodyfikowane w ramach osobnego procesu. Może być też tak, że front odeśle ci jakiś syf, a potem się do ciebie zgłosi, że backend nie działa

2024-11-12 17:11 UTC, Higunio320 commented on backend/src/main/java/pl/edu/pw/ee/backend/api/auth/account/AccountCreationServiceImpl.java
> +        log.info("Creating courier account : {}", request);
To prawda, dlatego napisałem że w czasie developmentu. Jak ktoś wykryje problem, to można odpalić debug i go odtworzyć, nie przebierając przy tym w tonie logów. Chyba, że zakładasz, że ten ktoś podeśle logi - wtedy się zgodzę. Kwestia przypadku, ja u siebie dawałem debug na pewno

2024-11-12 17:19 UTC, szymonpoltorak commented on backend/src/main/java/pl/edu/pw/ee/backend/api/auth/account/AccountCreationServiceImpl.java
> +        log.info("Creating courier account : {}", request);
na debug można przełączać część logów ale przełączanie wszystkiego na debug nie ma za bardzo sensu bo wtedy nie masz zielonego pojęcia co się działo w aplikacji podczas testowania lub użytkowania

2024-11-12 17:37 UTC, Higunio320 approved these changes

2024-11-13 11:20 UTC, merged